import About from '@/components/About'
import ContactMe from '@/components/ContactMe'
import Experience from '@/components/Experience'
import Header from '@/components/Header'
import Hero from '@/components/Hero'
import Projects from '@/components/Projects'
import Skills from '@/components/Skills'
import { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0'>

      <Head>
        <title>Krasulia/Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/portfolio.svg" />
      </Head>

      <Header />

      <section id='hero' className='snap-center'>
        <Hero />
      </section>

      <section id='about' className='snap-center'>
        <About />
      </section>

      <section id='skills' className='snap-center'>
        <Skills />
      </section>

      <section id='projects' className='snap-center'>
        <Projects />
      </section>

      <section id='contact-me' className='snap-center'>
        <ContactMe />
      </section>

      <Link href='#hero'>
        <div className='w-50 h-50 sticky bottom-5 right-5 cursor-pointer'>
          <Image src='/icons8-sort-up-96 (2).png' width={50} height={50} alt='arrow up'/>
        </div>
      </Link>

    </div>
  )
}
export default Home